name: Lua
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: wget -O - http://luajit.org/download/LuaJIT-2.0.4.tar.gz | tar xz
    - run: cd LuaJIT-2.0.4 && make && sudo make install INSTALL_TSYMNAME=lua && cd ..
    - run: wget -O - http://luarocks.org/releases/luarocks-2.2.2.tar.gz | tar xz || wget -O - http://keplerproject.github.io/luarocks/releases/luarocks-2.2.2.tar.gz | tar xz
    - run: cd luarocks-2.2.
    - run: ./configure --with-lua-include=/usr/local/include/luajit-2.0;
    - run: make build && sudo make install
    - run: cd ..
    - run: sudo luarocks install busted
    - run: ./test.sh
