name: Lua
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y lua5.3 luarocks liblua5.3-dev
    - run: sudo luarocks install busted
    - run: ./test.sh
